/* Formatted on 09/06/2022 7:30:05 AM (QP5 v5.139.911.3011) */
--FUNCTION TO RETURN THE PAYMENT INTSALLMENT NUMBER USING START AND END DATE
CREATE OR REPLACE FUNCTION GET_PAYMENT_INSTALL_NUMBER (START_DATE DATE,END_DATE DATE,
   CONTRACT_TYPE CONTRACTS.CONTRACT_PAYMENT_TYPE%TYPE)
   RETURN NUMBER
IS
--MONTHS BETWEEN START DATE AND END DATE OF THE CONTRACT
V_MONTHS  NUMBER;
BEGIN
    V_MONTHS :=MONTHS_BETWEEN(END_DATE,START_DATE);
   IF (CONTRACT_TYPE = 'ANNUAL')
   THEN
      RETURN V_MONTHS/12;
   ELSIF (CONTRACT_TYPE = 'QUARTER')
   THEN
      RETURN V_MONTHS/3;
   ELSIF (CONTRACT_TYPE = 'MONTHLY')
   THEN
      RETURN V_MONTHS/1;
   ELSIF (CONTRACT_TYPE = 'HALF_ANNUAL')
   THEN
      RETURN V_MONTHS/6;
   END IF;
END;
SHOW ERRORS;