/* Formatted on 10/06/2022 8:25:37 PM (QP5 v5.139.911.3011) */
--creating function to retrieve how the months for a specfic contract 
CREATE OR REPLACE FUNCTION fun_add_months (
   INSTALL_DATE    DATE,
   PAYMENT_TYPE    CONTRACTS.CONTRACT_PAYMENT_TYPE%TYPE)
   RETURN DATE
IS
BEGIN
   IF (PAYMENT_TYPE = 'ANNUAL')
   THEN
      RETURN ADD_MONTHS (INSTALL_DATE, 12);
   ELSIF (PAYMENT_TYPE = 'QUARTER')
   THEN
      RETURN ADD_MONTHS (INSTALL_DATE, 3);
   ELSIF (PAYMENT_TYPE = 'MONTHLY')
   THEN
      RETURN ADD_MONTHS (INSTALL_DATE, 1);
   ELSIF (PAYMENT_TYPE = 'HALF_ANNUAL')
   THEN
      RETURN ADD_MONTHS (INSTALL_DATE, 6);
   END IF;
END;

SHOW ERRORS;